module.exports=class{
    index(handle){
        handle.assign('pathBase',handle.req.pathBase);
        handle.render();
        handle.end();
    }

    post(handle){
        handle.loadBody(body=>{
            handle.assign({
                headers:handle.inspect(handle.req.headers),
                raw:handle.bodyParser.raw(body),
                parsed:handle.inspect(handle.bodyParser.multipart(body,handle)),
            });
            handle.render();
            handle.end();
        });
    }
};